[package]
name = "compiler-llvm"
edition = "2024"

build = "build.rs"

[dependencies]
syntax.workspace = true
mir.workspace = true
hir.workspace = true
anyhow.workspace = true

#inkwell = { version = "0.6.0", features = ["llvm18-1-no-llvm-linking"] }
inkwell = { version = "0.6.0", features = ["llvm18-1"] }

[build-dependencies]
anyhow.workspace = true

cc = "1.2.18"
regex-lite = "0.1.6"
semver = "1.0.26"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }