[package]
name = "compiler-llvm"
edition = "2024"

build = "build.rs"

[dependencies]
syntax.workspace = true
anyhow.workspace = true

inkwell = { version = "0.5.0", features = ["llvm18-0-no-llvm-linking"] }

[build-dependencies]
anyhow.workspace = true
lazy_static.workspace = true

cc = "1.1.13"
regex-lite = "0.1.6"
semver = "1.0.23"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }