[package]
name = "syntax"
edition = "2024"

[dependencies]
lasso.workspace = true

indexmap.workspace = true
lazy_static.workspace = true
serde.workspace = true

thiserror.workspace = true
anyhow.workspace = true
owo-colors.workspace = true