[package]
name = "hir"
edition = "2024"

[dependencies]
syntax.workspace = true
type_system.workspace = true
indexmap.workspace = true
serde.workspace = true

anyhow.workspace = true
lasso.workspace = true